# Generated by Django 3.2.9 on 2021-11-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211115_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='myapp.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(default='Nobody took the book', related_name='books', to='myapp.User'),
        ),
    ]
