# Generated by Django 3.2.9 on 2021-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211116_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(blank=True, default='Nobody took the book', null=True, related_name='user', to='myapp.User'),
        ),
    ]
