# Generated by Django 3.2.9 on 2021-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(default='Nobody took the book', related_name='user', to='myapp.User'),
        ),
    ]
